# Generated by Django 3.1.1 on 2020-09-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chowk',
            fields=[
                ('chowk_id', models.AutoField(primary_key=True, serialize=False)),
                ('road_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('signal_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('left_state', models.BooleanField(default=False)),
                ('right_state', models.BooleanField(default=False)),
                ('front_state', models.BooleanField(default=False)),
                ('chowk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_management_app.chowk')),
            ],
        ),
        migrations.CreateModel(
            name='Density',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.DecimalField(decimal_places=1, max_digits=1)),
                ('signal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_management_app.signal')),
            ],
        ),
    ]
