# Generated by Django 3.1.1 on 2020-09-23 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chowk',
            fields=[
                ('chowk_id', models.AutoField(primary_key=True, serialize=False)),
                ('chowk_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('signal_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('left_state', models.BooleanField(default=False)),
                ('right_state', models.BooleanField(default=False)),
                ('front_state', models.BooleanField(default=False)),
                ('car_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('bike_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('truck_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('density', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=4)),
                ('left_green_time', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('right_green_time', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('front_green_time', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('chowk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_management_app.chowk')),
            ],
        ),
    ]
