# Generated by Django 3.1.1 on 2020-09-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='signal_id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
