# Generated by Django 3.1.1 on 2020-09-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chowk',
            old_name='road_name',
            new_name='chowk_name',
        ),
    ]
