# Generated by Django 3.1.1 on 2020-09-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management_app', '0003_auto_20200921_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='bike_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='car_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='signal',
            name='truck_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
