# Generated by Django 3.1.1 on 2020-09-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management_app', '0003_numplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numplate',
            name='last_seen',
            field=models.DateTimeField(blank=True),
        ),
    ]
