# Generated by Django 3.1.1 on 2020-09-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_management_app', '0004_auto_20200922_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='density',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4),
        ),
    ]
